# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moderation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'moderation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10moderation.proto\x12\nmoderation\"W\n\x15ModerateObjectRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12$\n\x04type\x18\x02 \x01(\x0e\x32\x16.moderation.ObjectType\x12\x0c\n\x04text\x18\x03 \x01(\t\")\n\x16ModerateObjectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08*\x83\x01\n\nObjectType\x12\x1b\n\x17OBJECT_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n\x1bOBJECT_TYPE_MOD_DESCRIPTION\x10\x01\x12\x1c\n\x18OBJECT_TYPE_COMMENT_TEXT\x10\x02\x12\x19\n\x15OBJECT_TYPE_USER_NAME\x10\x03\x32l\n\x11ModerationService\x12W\n\x0eModerateObject\x12!.moderation.ModerateObjectRequest\x1a\".moderation.ModerateObjectResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moderation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBJECTTYPE']._serialized_start=165
  _globals['_OBJECTTYPE']._serialized_end=296
  _globals['_MODERATEOBJECTREQUEST']._serialized_start=32
  _globals['_MODERATEOBJECTREQUEST']._serialized_end=119
  _globals['_MODERATEOBJECTRESPONSE']._serialized_start=121
  _globals['_MODERATEOBJECTRESPONSE']._serialized_end=162
  _globals['_MODERATIONSERVICE']._serialized_start=298
  _globals['_MODERATIONSERVICE']._serialized_end=406
# @@protoc_insertion_point(module_scope)
