DATABASE_URL: "{vault:comment-service/prod#database_url}"
HOST: "{vault:comment-service/prod#host}"
PORT: "{vault:comment-service/prod#port}"

LOG_LEVEL: "WARN"
LOG_FORMAT: "%(asctime)s %(levelname)-8s [%(name)s] %(message)s"
LOG_DATEFMT: "%Y-%m-%d %H:%M:%S"
