name: "lint and test"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read
  pull-requests: write

jobs:
  lint-and-test:
    uses: esclient/tools/.github/workflows/lint-and-test-python.yml@6e3e64fee289eacd97170c58ba6b5fce2c8852eb
    with:
      python-version: "3.13.7"
      source: "commentservice"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
